In [20]:


# Loading model to compare the results
model = pickle.load(open('classifier.pkl','rb'))
# print(model.predict([[2, 9, 6]]))

<IPython.core.display.Javascript object>

In [21]:
X_rf2=np.array([[-0.4877952 , -0.25088379, -0.46378664, -0.51543986,  0.05784012,
       -0.0262922 , -0.10351188, -0.31929301,  0.40877389,  0.11968017,
       -0.0858903 , -0.39144008, -0.22090758, -0.2944085 , -0.10670318,
       -0.38822597, -0.05805714, -0.18386347, -0.30097441, -0.05389032,
       -0.29186744, -0.2492245 , -0.34337233, -0.37693497,  0.32080655,
       -0.13570975,  0.0219982 , -0.21989091,  0.23083947,  0.17173277]])
# X_rf2=ss.transform(X_rf2)
X_rf2_prediction=model.predict(X_rf2)

<IPython.core.display.Javascript object>

In [22]:
X_rf2_prediction

array([0])

In [23]:
Catagory=['No SIGN OF BREAST CANCER',' Yes breast cancer detected be carefull']

In [24]:
print(Catagory[int(X_rf2_prediction)])

No SIGN OF BREAST CANCER


In [25]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()


In [30]:
X_rf2=np.array([[ 1.37325734,  0.36318719,  1.29254295,  1.39312002, -0.60829613,
       -0.07993782,  0.24277219,  0.67513869, -0.85597344, -1.29896166,
        1.47064932, -0.81206704,  1.4289415 ,  1.44852743, -1.01379125,
       -0.56339254, -0.27204702,  0.40725139, -0.75978406, -1.00547962,
        1.71934692,  0.05256312,  1.68197529,  1.68648542, -0.7636134 ,
       -0.16099207,  0.02979422,  0.93019499, -0.58958803, -0.972629  ]])
# X_rf2=ss.transform(X_rf2)
X_rf2_prediction=model.predict(X_rf2)

<IPython.core.display.Javascript object>

In [31]:
X_rf2_prediction

array([1])

In [32]:
print(Catagory[int(X_rf2_prediction)])

 Yes breast cancer detected be carefull


array([0])